### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by danielcarvalho99** [danielcarvalho99/Projeto-NLP#1]
- [ ] Treinar o modelo e avaliar suas métricas
- [ ] Subir o modelo na HuggingFace
- [x] Melhorar a interface (Sortear review com um botão para ativar um df.sample())
- [ ] Fazer um possível relatório
- [ ] Incluir solução simbólica
